### ISSUE TITLE
createHeaderScanStruct no longer exists (commented out), but referenced by e.g. StaticScan/staticscanitemmodel.cpp

### ISSUE THREAD

**Issue by skolpadda** [horsicq/SpecAbstract#1]
Is there a plan to replace this method? My build is currently broken until I can find a way to pin the dependencies at an earlier version.

**Comment by horsicq** [comment]
Thanks a lot for testing! Fixed: https://github.com/horsicq/SpecAbstract/commit/a255e3e8bde102c9ba93de4a82ea2b6e8a2f6a09
